### ISSUE TITLE
Install for explaining_with_counterfactuals.ipynb

### ISSUE THREAD

**Issue by pitmanme** [PatWalters/practical_cheminformatics_posts#6]
Hi Pat, 

Fantastic tutorial on counterfactuals! Posting this here in case anybody else chooses to install the listed libraries to run your tutorial and Jupyter notebook. The numpy version must be less than 1.24 and for exmol the python version must be less than 3.10 (down to some version). The install steps that worked for us is:

conda install pip python=3.9
pip install rdkit PyTDC useful_rdkit_utils tqdm scikit-learn numpy<1.24 seaborn exmol pandas mols2grid crem

**Comment by PatWalters** [comment]
Thank you for the note and the installation instructions.  I updated the README with your instructions.
